---

- name: Gather package facts
  package_facts:
  check_mode: no
  tags:
    - yum

- { import_tasks: keys.yml, tags: ['cvmfs', 'keys'] }
- { import_tasks: yum.yml, tags: ['cvmfs', 'yum'] }
- { import_tasks: users.yml, tags: ['cvmfs', 'users'] }
- { import_tasks: storage.yml, tags: ['cvmfs', 'storage'], when: cvmfs_client_configure_storage | bool }
- { import_tasks: packages.yml, tags: ['cvmfs', 'packages'] }
- { import_tasks: config.yml, tags: ['cvmfs', 'config'] }

- name: CVMFS tests
  include_tasks:
    file: tasks/test.yml
  tags: ['cvmfs', 'test']
  when: "cvmfs_tests is defined"

- name: Package cvmfs
  package:
    name: cvmfs
    state: latest

